In [3]:
import tensorflow as tf

In [5]:
# Verify TensorFlow version
print(tf.__version__)

# Example: Create a simple TensorFlow constant
hello_tensor = tf.constant("Hello, TensorFlow!")
print(hello_tensor)

2.20.0
tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


In [7]:
con1 =tf.constant(10)
con2 = tf.constant(20)
con3 = tf.constant(False)

In [8]:
print(con1,con2,con3)

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(20, shape=(), dtype=int32) tf.Tensor(False, shape=(), dtype=bool)



Instructions for updating:
non-resource variables are not supported in the long term


In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

con1 = tf.constant(5)
con2 = tf.constant(10)
con3 = con1 + con2

with tf.Session() as ses:
    print(ses.run([con1, con2, con3]))


[np.int32(5), np.int32(10), np.int32(15)]


In [16]:
addition = tf.constant([1,2,3,4,5])+tf.constant([10,9,8,7,6])
multiplication = tf.constant([1,2,3,4,5]) * tf.constant([10,9,8,7,6])

In [17]:
with tf.Session() as ses:
    print(ses.run([addition,multiplication]))

[array([11, 11, 11, 11, 11], dtype=int32), array([10, 18, 24, 28, 30], dtype=int32)]


In [19]:
str1 = tf.constant("I love ")
str2 = tf.constant("TenssorFlow")

In [20]:
with tf.Session() as ses:
    print(ses.run([str1 + str2]))

[b'I love TenssorFlow']


In [26]:
#placeholder 

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.placeholder(tf.int32)
y = x * 5

with tf.Session() as sess:
    result = sess.run(y, feed_dict={x: 2})  # ✅ Feed value to x
    print(result)  # 15


10


In [27]:
with tf.Session() as sess:
    result = sess.run(y, feed_dict={x:[2,4,6,8]}) 
    print(result) 

[10 20 30 40]


In [31]:
str_name = tf.placeholder(tf.string)
my_name = "I am " + str_name

In [35]:
with tf.Session() as sess:
    result = sess.run(my_name, feed_dict={str_name:['Sam','Bob','Charlie']})
    print(result)

[b'I am Sam' b'I am Bob' b'I am Charlie']


In [36]:
#variable 

var1 = tf.Variable([20],tf.int32)

In [37]:
init = tf.global_variables_initializer()

In [38]:
ses = tf.Session()

In [39]:
ses.run(init)

In [40]:
ses.run(var1)

array([20], dtype=int32)

In [42]:
update_var1 = tf.assign(var1,[25])

In [43]:
ses.run(update_var1)

array([25], dtype=int32)

In [44]:
#linear model 

w = tf.Variable([10],tf.int32)
b = tf.Variable([5],tf.int32)
x = tf.placeholder(tf.int32)

In [45]:
linear_model = w*x + b

In [46]:
init1 = tf.global_variables_initializer()
ses.run(init1)

In [47]:
ses.run(linear_model,feed_dict={x:[1,2,3,4,5]})

array([15, 25, 35, 45, 55], dtype=int32)

In [52]:
import tensorflow as tf

In [60]:
# Basics
hello = tf.constant('Hello,Hridoy!')

In [61]:
type(hello)

tensorflow.python.framework.ops.SymbolicTensor

In [62]:
tf.print(hello)

<tf.Operation 'PrintV2_3' type=PrintV2>

In [63]:
import tensorflow as tf

# Enable TensorFlow 1.x behavior
tf.compat.v1.disable_eager_execution()

# Define a tensor with random values
random_tensor_var_one = tf.Variable(tf.random.uniform([2, 3, 4], minval=0, maxval=10, dtype=tf.int32))

In [64]:
# Create a session
sess = tf.compat.v1.Session()

# Initialize all variables
sess.run(tf.compat.v1.global_variables_initializer())

In [65]:
# Run the session to get the value of the tensor
tensor_value = sess.run(random_tensor_var_one)

# Print the tensor value
print("Tensor value:", tensor_value)

# Close the session
sess.close()

Tensor value: [[[3 4 6 5]
  [9 8 4 3]
  [7 5 3 2]]

 [[1 7 7 9]
  [0 2 2 7]
  [0 4 5 0]]]


In [66]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

Tensor("Const_19:0", shape=(2, 2), dtype=int32)


In [70]:
#scalar value
myarr = tf.fill((5,5),5)

